/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import dao.ConsultasDAO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;

/**
 *
 * @author Laryssa
 */
public class TelaFluxodeCaixa extends javax.swing.JFrame {

    /**
     * Creates new form TelaFluxodeCaixa
     */
    public TelaFluxodeCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableFluxo = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jDataFinal = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jDataInicial = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBuscarDatas = new javax.swing.JButton();
        txtValorTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 60, 60);

        jtableFluxo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Pedido", "Cliente", "Data", "Pizza", "Bebida", "Valor "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtableFluxo);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 140, 860, 290);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("VALOR TOTAL:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 450, 120, 20);

        try {
            jDataFinal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##      /  ##     /  ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jDataFinal);
        jDataFinal.setBounds(510, 80, 120, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Data Final:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 80, 80, 14);

        try {
            jDataInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##      /  ##     /  ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jDataInicial);
        jDataInicial.setBounds(250, 80, 120, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("FLUXO DE CAIXA - BELLA PIZZA");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 20, 390, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Data Inicial:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 80, 80, 14);

        btnBuscarDatas.setText("Buscar");
        btnBuscarDatas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDatasActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarDatas);
        btnBuscarDatas.setBounds(750, 70, 90, 40);

        txtValorTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtValorTotal.setForeground(new java.awt.Color(51, 51, 255));
        txtValorTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txtValorTotal);
        txtValorTotal.setBounds(700, 450, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaP.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 510);

        setSize(new java.awt.Dimension(902, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarDatasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDatasActionPerformed
      /*DefaultTableModel model = (DefaultTableModel) jtableFluxo.getModel();
        String dataInicial = jDataInicial.getText();
        String dataFinal = jDataFinal.getText();
        ConsultasDAO consulta = new ConsultasDAO();
        List<Cliente> clientes = null;
        try {
            clientes = consulta.getClientes();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro sql");
        }
        int iguais = 0;
        for (Cliente nomeClienteAtual : clientes) {
            if(nomeCliente.toLowerCase().equals(nomeClienteAtual.getNome().toString().toLowerCase()))   {
                model.addRow(new Object[]{nomeClienteAtual.getNome().toLowerCase(), nomeClienteAtual.getTelefone(), ("Rua: "+nomeClienteAtual.getRua() + " "+ nomeClienteAtual.getNumero() + " Bairro: " +
                        nomeClienteAtual.getBairro()), nomeClienteAtual.getComplemento()});
                iguais++;
            }
        }

        if (iguais == 0) {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
        }*/
    }//GEN-LAST:event_btnBuscarDatasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFluxodeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFluxodeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFluxodeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFluxodeCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFluxodeCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarDatas;
    private javax.swing.JFormattedTextField jDataFinal;
    private javax.swing.JFormattedTextField jDataInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableFluxo;
    private javax.swing.JLabel txtValorTotal;
    // End of variables declaration//GEN-END:variables
}
