/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Winy
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jLabelCadastro = new javax.swing.JLabel();
        jButtonCadClientes = new javax.swing.JButton();
        jButtonCadFunc = new javax.swing.JButton();
        jLabelPedidos = new javax.swing.JLabel();
        jButtonPedidos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabelPainelFundo = new javax.swing.JLabel();
        jButtonFecharBemVindo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel1FundoTelaPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadClientes = new javax.swing.JMenuItem();
        jMenuItemCadFuncionarios = new javax.swing.JMenuItem();
        jMenuPedidos = new javax.swing.JMenu();
        jMenuCardapio = new javax.swing.JMenu();
        jMenuItemCardapioPizza = new javax.swing.JMenuItem();
        jMenuItemcardapioRefri = new javax.swing.JMenuItem();
        jMenuRelatorios = new javax.swing.JMenu();
        jMenuItemRelatorioCaixa = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jLabelCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCadastro.setText("Cadastros");
        jPanelInternal.add(jLabelCadastro);
        jLabelCadastro.setBounds(20, 10, 80, 30);

        jButtonCadClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        jButtonCadClientes.setToolTipText("Clientes");
        jPanelInternal.add(jButtonCadClientes);
        jButtonCadClientes.setBounds(10, 40, 90, 80);

        jButtonCadFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/funcionariopeq.png"))); // NOI18N
        jButtonCadFunc.setToolTipText("Funcionarios");
        jPanelInternal.add(jButtonCadFunc);
        jButtonCadFunc.setBounds(120, 40, 90, 80);

        jLabelPedidos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPedidos.setText("Pedidos");
        jPanelInternal.add(jLabelPedidos);
        jLabelPedidos.setBounds(390, 10, 100, 20);

        jButtonPedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pizzap.png"))); // NOI18N
        jButtonPedidos.setToolTipText("Pedidos Clientes");
        jPanelInternal.add(jButtonPedidos);
        jButtonPedidos.setBounds(390, 40, 80, 80);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cardapio");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(680, 10, 110, 20);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cardapio.png"))); // NOI18N
        jButton1.setToolTipText("Cardapio Pizzas");
        jPanelInternal.add(jButton1);
        jButton1.setBounds(680, 40, 70, 80);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Relatorios");
        jPanelInternal.add(jLabel3);
        jLabel3.setBounds(20, 160, 100, 30);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/caixa.png"))); // NOI18N
        jButton2.setToolTipText("Caixa");
        jPanelInternal.add(jButton2);
        jButton2.setBounds(20, 190, 80, 80);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/internal.jpg"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 990, 360);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 50, 990, 360);

        jButtonFecharBemVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jButtonFecharBemVindo.setToolTipText("Fechar Tela Bem Vindo");
        jButtonFecharBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBemVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharBemVindo);
        jButtonFecharBemVindo.setBounds(830, 0, 60, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(14, 10, 290, 30);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(0, 110, 900, 440);

        jLabel1FundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/telaP.png"))); // NOI18N
        getContentPane().add(jLabel1FundoTelaPrincipal);
        jLabel1FundoTelaPrincipal.setBounds(0, 0, 1020, 550);

        jMenuCadastro.setText("Cadastro");

        jMenuItemCadClientes.setText("Clientes");
        jMenuCadastro.add(jMenuItemCadClientes);

        jMenuItemCadFuncionarios.setText("Funcionarios");
        jMenuCadastro.add(jMenuItemCadFuncionarios);

        jMenuBar1.add(jMenuCadastro);

        jMenuPedidos.setText("Pedidos");
        jMenuBar1.add(jMenuPedidos);

        jMenuCardapio.setText("Cardapio");

        jMenuItemCardapioPizza.setText("Pizzas");
        jMenuCardapio.add(jMenuItemCardapioPizza);

        jMenuItemcardapioRefri.setText("Refrigerante");
        jMenuCardapio.add(jMenuItemcardapioRefri);

        jMenuBar1.add(jMenuCardapio);

        jMenuRelatorios.setText("Relatorios");

        jMenuItemRelatorioCaixa.setText("Caixa");
        jMenuRelatorios.add(jMenuItemRelatorioCaixa);

        jMenuBar1.add(jMenuRelatorios);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1032, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBemVindoActionPerformed
       jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBemVindoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadClientes;
    private javax.swing.JButton jButtonCadFunc;
    private javax.swing.JButton jButtonFecharBemVindo;
    private javax.swing.JButton jButtonPedidos;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1FundoTelaPrincipal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCadastro;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelPedidos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuCardapio;
    private javax.swing.JMenuItem jMenuItemCadClientes;
    private javax.swing.JMenuItem jMenuItemCadFuncionarios;
    private javax.swing.JMenuItem jMenuItemCardapioPizza;
    private javax.swing.JMenuItem jMenuItemRelatorioCaixa;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemcardapioRefri;
    private javax.swing.JMenu jMenuPedidos;
    private javax.swing.JMenu jMenuRelatorios;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
